#ifndef OPINFO
#error "You must define OPINFO macro before include this file"
#endif

OPINFO(OP_COMMA,         1,    ",",      Comma,          NOP)
OPINFO(OP_ASSIGN,        2,    "=",      Assignment,     NOP)
OPINFO(OP_OR,            4,    "||",     Binary,         NOP)
OPINFO(OP_SEPARATOR,     4,    "|",      Binary,         NOP)
OPINFO(OP_AND,           5,    "&&",     Binary,         NOP)
OPINFO(OP_COLON,         5,    ":",      Binary,         NOP)
OPINFO(OP_EQUAL,         9,    "==",     Binary,         JE)
OPINFO(OP_UNEQUAL,       9,    "!=",     Binary,         JNE)
OPINFO(OP_GREAT,         10,   ">",      Binary,         JG)
OPINFO(OP_LESS,          10,   "<",      Binary,         JL)
OPINFO(OP_GREAT_EQ,      10,   ">=",     Binary,         JGE)
OPINFO(OP_LESS_EQ,       10,   "<=",     Binary,         JLE)
OPINFO(OP_ADD,           12,   "+",      Binary,         ADD)
OPINFO(OP_SUB,           12,   "-",      Binary,         SUB)
OPINFO(OP_MUL,           13,   "*",      Binary,         MUL)
OPINFO(OP_DIV,           13,   "/",      Binary,         DIV)
OPINFO(OP_MOD,           13,   "%",      Binary,         MOD)
OPINFO(OP_COMP,          14,   "~",      Unary,          BCOM)
OPINFO(OP_NEG,           14,   "-",      Unary,          NEG)
OPINFO(OP_NOT,           14,   "!",      Unary,          NOP)
OPINFO(OP_RELATIVE,      14,   "'",      Unary,          NOP)
OPINFO(OP_INDEX,         15,   "[]",     Postfix,        NOP)
OPINFO(OP_CALL,          15,   "call",   Postfix,        NOP)
OPINFO(OP_MEMBER,        15,   ".",      Postfix,        NOP)
OPINFO(OP_REPEAT,        15,   "*",      Postfix,        DUP)
OPINFO(OP_ID,            16,   "id",     Primary,        NOP)
OPINFO(OP_CONST,         16,   "const",  Primary,        NOP)
OPINFO(OP_ATTR,          16,   "attr",   Primary,        NOP)
OPINFO(OP_STR,           16,   "str",    Primary,        NOP)
OPINFO(OP_NONE,          17,   "nop",    Error,          NOP)
